namespace: flask1
resources:
  - ../../base

patches:
  - patch: |-
  - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        - name: MAIN_TEXT
          value: "Hello from folder #1"
    target: 
      kind: Deployment
      namespace: flask1
