apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flask1
resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: flask
    path: ./deployment-patch.yaml

