apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flask1
resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/env/1"
        value:
          name: MAIN_TEXT
          value: "Hello from folder #1"
    target:
      kind: Deployment
      name: flask
