apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  template:
    spec:
      containers:
        - name: flask-2
          env:
            - name: MAIN_TEXT
              value: "Hello from second folder"
