apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  template:
    spec:
      containers:
        - name: dev1s/my-flask-app
          env:
            - name: MAIN_TEXT
              value: "Hello from second folder"
