apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flask2
resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: MAIN_TEXT
          value: "Hello from second folder"
    target:
      kind: Deployment
      name: flask
